# This file contains values from Cookiecutter

default_context:
  project_name: "flask_credentials"
  project_description: "Awesome `flask_credentials` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "zenteach"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "zenteach"
  email: "connect@ngetahun.me"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
